#!/usr/bin/env bash
# This file is auto-generated by the GraphyFlow backend.

set -euo pipefail

usage() {
    cat <<'USAGE'
Usage: ./run.sh [sw_emu|hw_emu|hw] [dataset]

Run the emitted GraphyFlow project in the selected mode.

Examples:
  ./run.sh sw_emu /path/to/graph.txt
  ./run.sh hw_emu /path/to/graph.txt
  ./run.sh hw /path/to/graph.txt

Notes:
  - Build the host first with: make exe TARGET=<mode>
  - Build the xclbin first with: make all TARGET=<mode> [DEVICE=<platform>]
  - If your shell is not already prepared for XRT/Vitis, set GRAPHYFLOW_ENV_SH
    to the environment script you normally source before running.
USAGE
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

TARGET="${1:-sw_emu}"
DATASET="${2:-$SCRIPT_DIR/graph.txt}"
EXECUTABLE="graphyflow_host"
XCLBIN_NAME="graphyflow_kernels"
XCLBIN_FILE="$SCRIPT_DIR/xclbin/${XCLBIN_NAME}.${TARGET}.xclbin"
XRT_SETUP_FALLBACK="/opt/xilinx/xrt/setup.sh"

source_env_script() {
    local script_path="$1"
    set +e
    set +u
    set +o pipefail
    # shellcheck disable=SC1090
    source "$script_path"
    local rc=$?
    set -e
    set -u
    set -o pipefail
    return "$rc"
}

case "$TARGET" in
    sw_emu|hw_emu)
        export XCL_EMULATION_MODE="$TARGET"
        ;;
    hw)
        unset XCL_EMULATION_MODE
        ;;
    -h|--help)
        usage
        exit 0
        ;;
    *)
        echo "Error: mode must be one of: sw_emu, hw_emu, hw" >&2
        usage >&2
        exit 2
        ;;
esac

export XRT_INI_PATH="$SCRIPT_DIR/xrt.ini"
if [[ "$TARGET" != "hw" && -z "${EMCONFIG_PATH:-}" && -f "$SCRIPT_DIR/emconfig.json" ]]; then
    export EMCONFIG_PATH="$SCRIPT_DIR"
fi
if [[ "$TARGET" != "hw" && "${GRAPHYFLOW_RESET_EMU_STATE:-1}" == "1" ]]; then
    rm -rf "$SCRIPT_DIR/.run" "$SCRIPT_DIR/.Xil"
fi

if [[ -n "${GRAPHYFLOW_ENV_SH:-}" ]]; then
    if [[ ! -f "${GRAPHYFLOW_ENV_SH}" ]]; then
        echo "Error: GRAPHYFLOW_ENV_SH does not exist: ${GRAPHYFLOW_ENV_SH}" >&2
        exit 1
    fi
    if ! source_env_script "${GRAPHYFLOW_ENV_SH}"; then
        echo "Error: failed to source GRAPHYFLOW_ENV_SH: ${GRAPHYFLOW_ENV_SH}" >&2
        exit 1
    fi
elif [[ -f "$XRT_SETUP_FALLBACK" ]]; then
    if ! source_env_script "$XRT_SETUP_FALLBACK"; then
        echo "Error: failed to source XRT runtime setup: $XRT_SETUP_FALLBACK" >&2
        exit 1
    fi
elif [[ -n "${XILINX_XRT:-}" || -n "${XILINX_VITIS:-}" ]]; then
    :
else
    echo "Warning: no GraphyFlow/XRT environment script was sourced." >&2
    echo "Set GRAPHYFLOW_ENV_SH or source your Vitis/XRT environment before running if the host fails to start." >&2
fi

if [[ -f /lib/x86_64-linux-gnu/libOpenCL.so.1 ]]; then
    export LD_PRELOAD="/lib/x86_64-linux-gnu/libOpenCL.so.1${LD_PRELOAD:+ ${LD_PRELOAD}}"
fi

if [[ ! -f "$XCLBIN_FILE" ]]; then
    echo "Error: xclbin file not found at '$XCLBIN_FILE'" >&2
    echo "Build it with: make all TARGET=${TARGET}" >&2
    exit 1
fi

if [[ ! -x "$SCRIPT_DIR/${EXECUTABLE}" ]]; then
    echo "Error: host executable not found: ${SCRIPT_DIR}/${EXECUTABLE}" >&2
    echo "Build it with: make exe TARGET=${TARGET}" >&2
    exit 1
fi

if [[ ! -f "$DATASET" ]]; then
    echo "Error: dataset not found at '$DATASET'" >&2
    echo "Pass an explicit dataset path, for example: ./run.sh ${TARGET} /path/to/graph.txt" >&2
    exit 1
fi

if [[ -z "${GRAPHYFLOW_APP:-}" ]]; then
    GRAPHYFLOW_APP="$(basename "$SCRIPT_DIR")"
fi
export GRAPHYFLOW_APP

: "${GRAPHYFLOW_ALLOW_MISMATCH:=1}"
export GRAPHYFLOW_ALLOW_MISMATCH

echo "--- Running for target: $TARGET ---"
if [[ -n "${XCL_EMULATION_MODE:-}" ]]; then
    echo "XCL_EMULATION_MODE set to: $XCL_EMULATION_MODE"
else
    echo "Running on hardware, XCL_EMULATION_MODE is unset."
fi
echo "Using xclbin: $XCLBIN_FILE"
echo "Using dataset: $DATASET"

"$SCRIPT_DIR/${EXECUTABLE}" "$XCLBIN_FILE" "$DATASET"
