/**
 * graph_preprocess.cpp — No-L1 (naive) preprocess mode.
 *
 * Simplified 2-partition preprocessing without throughput-based repartitioning.
 * Distributes destination vertices by a fixed 80/20 ratio between little and
 * big partitions, sorted by indegree. Edges are split evenly across pipelines.
 *
 * This file is auto-generated by Graph.hls with no_l1_preprocess: true.
 * It uses the same PartitionGroup/PartitionContainer interface as the L1
 * version so the rest of the host code works unchanged.
 */
#include "graph_preprocess.h"
#include <algorithm>
#include <cmath>
#include <iostream>
#include <numeric>
#include <set>
#include <vector>

struct Edge {
    int src, dest, weight;
};

PartitionContainer partitionGraph(const GraphCSR *graph,
                                  double /* big_edge_per_ms_per_pipe */,
                                  double /* little_edge_per_ms_per_pipe */) {
    std::cout << "--- Starting Graph Partitioning (no-L1 / naive mode) ---"
              << std::endl;
    PartitionContainer container;
    container.num_graph_vertices = graph->num_vertices;
    container.num_graph_edges = graph->num_edges;

    // Compute out-degrees for the whole graph
    container.graph_out_degrees.resize(graph->num_vertices, 0);
    for (int u = 0; u < graph->num_vertices; ++u) {
        container.graph_out_degrees[u] =
            (uint32_t)(graph->offsets[u + 1] - graph->offsets[u]);
    }

    std::cout << "Global graph: " << graph->num_vertices << " vertices, "
              << graph->num_edges << " edges." << std::endl;
    std::cout << "[INFO] no-L1 mode: 1 little group (" << LITTLE_KERNEL_NUM
              << " pipelines) + 1 big group (" << BIG_KERNEL_NUM
              << " pipelines), max dst little=" << LITTLE_MAX_DST
              << " big=" << BIG_MAX_DST << std::endl;

    // --- PHASE 1: Collect unique destination vertices sorted by indegree ---
    std::unordered_map<int, int> node_indegrees;
    for (int i = 0; i < graph->num_edges; ++i) {
        node_indegrees[graph->columns[i]]++;
    }
    std::vector<int> unique_dsts;
    unique_dsts.reserve(node_indegrees.size());
    for (auto &kv : node_indegrees) {
        unique_dsts.push_back(kv.first);
    }
    std::sort(unique_dsts.begin(), unique_dsts.end(),
              [&node_indegrees](int a, int b) {
                  return node_indegrees[a] > node_indegrees[b];
              });
    std::cout << "[PHASE 1] " << unique_dsts.size()
              << " unique destination vertices (sorted by indegree)."
              << std::endl;

    // --- PHASE 2: Split destinations 80/20 between little and big ---
    size_t total_dsts = unique_dsts.size();
    size_t little_dst_count =
        std::min((size_t)LITTLE_MAX_DST, total_dsts);
    if (little_dst_count == total_dsts) {
        little_dst_count = (size_t)(total_dsts * 0.8);
    }
    size_t big_dst_count =
        std::min((size_t)BIG_MAX_DST, total_dsts - little_dst_count);

    std::set<int> little_dst_set, big_dst_set;
    std::unordered_map<int, int> dst_to_partition; // 0=little, 1=big

    for (size_t i = 0; i < little_dst_count; ++i) {
        little_dst_set.insert(unique_dsts[i]);
        dst_to_partition[unique_dsts[i]] = 0;
    }
    for (size_t i = little_dst_count;
         i < little_dst_count + big_dst_count; ++i) {
        big_dst_set.insert(unique_dsts[i]);
        dst_to_partition[unique_dsts[i]] = 1;
    }

    std::cout << "[PHASE 2] Little: " << little_dst_count
              << " dsts, Big: " << big_dst_count << " dsts." << std::endl;

    // --- PHASE 3: Assign edges to little/big based on destination ---
    std::vector<Edge> little_edges, big_edges;
    for (int u = 0; u < graph->num_vertices; ++u) {
        for (int i = graph->offsets[u]; i < graph->offsets[u + 1]; ++i) {
            int v = graph->columns[i];
            int w = graph->weights[i];
            auto it = dst_to_partition.find(v);
            if (it == dst_to_partition.end()) {
                std::cerr << "[ERROR] Destination vertex " << v
                          << " not in any partition!" << std::endl;
                exit(1);
            }
            if (it->second == 0) {
                little_edges.push_back({u, v, w});
            } else {
                big_edges.push_back({u, v, w});
            }
        }
    }
    std::cout << "[PHASE 3] Little: " << little_edges.size()
              << " edges, Big: " << big_edges.size() << " edges."
              << std::endl;

    // --- PHASE 4: Process each partition ---
    auto process_partition =
        [&](const std::vector<Edge> &partition_edges,
            const std::set<int> &partition_dst_nodes, bool is_dense,
            int num_pipelines) -> PartitionDescriptor {
        PartitionDescriptor pd;
        pd.is_dense = is_dense;
        pd.num_pipelines = num_pipelines;

        if (partition_edges.empty()) {
            pd.num_edges = 0;
            pd.num_vertices = 0;
            pd.num_dsts = 0;
            return pd;
        }

        // Collect unique vertices
        std::set<int> local_vertices_set;
        for (const auto &edge : partition_edges) {
            local_vertices_set.insert(edge.src);
            local_vertices_set.insert(edge.dest);
        }

        // Map destination vertices first (lower IDs), then sources
        std::vector<int> ordered_dst(partition_dst_nodes.begin(),
                                     partition_dst_nodes.end());
        std::srand(42);
        std::random_shuffle(ordered_dst.begin(), ordered_dst.end());

        int local_id = 0;
        for (int gid : ordered_dst) {
            pd.vtx_map[gid] = local_id;
            pd.vtx_map_rev[local_id] = gid;
            local_id++;
        }
        pd.num_dsts = partition_dst_nodes.size();

        for (int gid : local_vertices_set) {
            if (pd.vtx_map.find(gid) == pd.vtx_map.end()) {
                pd.vtx_map[gid] = local_id;
                pd.vtx_map_rev[local_id] = gid;
                local_id++;
            }
        }
        pd.num_vertices = local_vertices_set.size();

        // Rewrite edges with local IDs and sort by src
        std::vector<Edge> local_edges;
        local_edges.reserve(partition_edges.size());
        for (const auto &ge : partition_edges) {
            local_edges.push_back(
                {pd.vtx_map[ge.src], pd.vtx_map[ge.dest], ge.weight});
        }
        std::sort(local_edges.begin(), local_edges.end(),
                  [](const Edge &a, const Edge &b) {
                      return a.src < b.src;
                  });
        pd.num_edges = local_edges.size();

        // Distribute edges evenly across pipelines
        pd.pipeline_edges.resize(num_pipelines);
        int edges_per_pipeline =
            (pd.num_edges + num_pipelines - 1) / num_pipelines;

        for (int pip = 0; pip < num_pipelines; ++pip) {
            pd.pipeline_edges[pip].pipeline_id = pip;
            int start_idx =
                std::min(pip * edges_per_pipeline, (int)pd.num_edges);
            int end_idx =
                std::min(start_idx + edges_per_pipeline, (int)pd.num_edges);

            std::vector<Edge> cur_pip_edges;
            uint32_t last_src_buffer = 0;
            int last_src_id = 0;
            for (int ei = start_idx; ei < end_idx; ++ei) {
                auto &le = local_edges[ei];
                uint32_t cur_src_buffer =
                    (uint32_t)std::floor((double)le.src / SRC_BUFFER_SIZE);
                if (is_dense && cur_src_buffer != last_src_buffer) {
                    uint32_t mod8 = cur_pip_edges.size() % 8;
                    if (mod8 != 0) {
                        for (uint32_t pad = 0; pad < (8 - mod8); pad++) {
                            cur_pip_edges.push_back(
                                {last_src_id, 0x7FFFFFFF, 1});
                        }
                    }
                    last_src_buffer = cur_src_buffer;
                }
                last_src_id = le.src;
                cur_pip_edges.push_back({le.src, le.dest, le.weight});
            }

            pd.pipeline_edges[pip].num_edges = cur_pip_edges.size();
            int padding_size =
                (8 - (pd.pipeline_edges[pip].num_edges % 8)) % 8;
            pd.pipeline_edges[pip].num_edges += padding_size;

            // Build CSR for this pipeline
            pd.pipeline_edges[pip].offsets.resize(pd.num_vertices + 1, 0);
            pd.pipeline_edges[pip].columns.reserve(
                pd.pipeline_edges[pip].num_edges);
            pd.pipeline_edges[pip].weights.reserve(
                pd.pipeline_edges[pip].num_edges);

            std::vector<int> out_degree(pd.num_vertices, 0);
            for (size_t j = 0; j < cur_pip_edges.size(); ++j) {
                out_degree[cur_pip_edges[j].src]++;
                if (j == cur_pip_edges.size() - 1) {
                    for (int p = 0; p < padding_size; ++p)
                        out_degree[cur_pip_edges[j].src]++;
                }
            }

            pd.pipeline_edges[pip].offsets[0] = 0;
            for (int v = 0; v < (int)pd.num_vertices; ++v) {
                pd.pipeline_edges[pip].offsets[v + 1] =
                    pd.pipeline_edges[pip].offsets[v] + out_degree[v];
            }

            for (size_t j = 0; j < cur_pip_edges.size(); ++j) {
                pd.pipeline_edges[pip].columns.push_back(
                    cur_pip_edges[j].dest);
                pd.pipeline_edges[pip].weights.push_back(
                    cur_pip_edges[j].weight);
                if (j == cur_pip_edges.size() - 1) {
                    for (int p = 0; p < padding_size; ++p) {
                        pd.pipeline_edges[pip].columns.push_back(0x7FFFFFFF);
                        pd.pipeline_edges[pip].weights.push_back(1);
                    }
                }
            }
        }

        return pd;
    };

    // Process little partition
    PartitionDescriptor little_pd = process_partition(
        little_edges, little_dst_set, true, LITTLE_KERNEL_NUM);
    std::cout << "  Little: " << little_pd.num_vertices << " vertices, "
              << little_pd.num_dsts << " dsts, " << little_pd.num_edges
              << " edges -> " << little_pd.num_pipelines << " pipelines."
              << std::endl;

    // Process big partition
    PartitionDescriptor big_pd = process_partition(
        big_edges, big_dst_set, false, BIG_KERNEL_NUM);
    std::cout << "  Big: " << big_pd.num_vertices << " vertices, "
              << big_pd.num_dsts << " dsts, " << big_pd.num_edges
              << " edges -> " << big_pd.num_pipelines << " pipelines."
              << std::endl;

    // Wrap into PartitionGroup (single group each, compatible with L1 host)
    PartitionGroup little_group;
    little_group.group_id = 0;
    little_group.pipeline_offset = 0;
    little_group.num_pipelines = LITTLE_KERNEL_NUM;
    little_group.partitions.push_back(little_pd);

    PartitionGroup big_group;
    big_group.group_id = 0;
    big_group.pipeline_offset = 0;
    big_group.num_pipelines = BIG_KERNEL_NUM;
    big_group.partitions.push_back(big_pd);

    container.dense_groups.push_back(little_group);
    container.sparse_groups.push_back(big_group);
    container.num_dense_groups = 1;
    container.num_sparse_groups = 1;
    container.num_dense_partitions = 1;
    container.num_sparse_partitions = 1;

    // Build flattened partition index mappings
    container.dense_partition_order.push_back({0, 0});
    container.sparse_partition_order.push_back({0, 0});
    container.dense_partition_indices.resize(1);
    container.dense_partition_indices[0].push_back(0);
    container.sparse_partition_indices.resize(1);
    container.sparse_partition_indices[0].push_back(0);

    std::cout << "[SUCCESS] no-L1 partitioning complete: 1 dense + 1 sparse."
              << std::endl;
    return container;
}
