/**
 * graph_preprocess.cpp — No-L1 (naive) preprocess mode.
 *
 * Simplified 2-partition preprocessing without throughput-based repartitioning.
 * Distributes destination vertices by a fixed 80/20 ratio between little and
 * big partitions, sorted by indegree.
 *
 * This file is auto-generated by Graph.hls with no_l1_preprocess: true.
 * It reuses the normal partition formatter so the emitted host/kernel contract
 * stays consistent with standard preprocess mode.
 */
#include "graph_preprocess.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <numeric>
#include <set>
#include <vector>

#if EDGES_PER_WORD <= 0
#error "EDGES_PER_WORD must be positive"
#endif

struct Edge {
    int src;
    int dest;
    int weight;
    std::vector<uint64_t> props;
};

static inline size_t pad_to_word(size_t n) {
    const size_t mod = n % EDGES_PER_WORD;
    return mod == 0 ? 0 : (EDGES_PER_WORD - mod);
}

PartitionContainer partitionGraph(const GraphCSR *graph,
                                  double /* big_edge_per_ms_per_pipe */,
                                  double /* little_edge_per_ms_per_pipe */) {
    std::cout << "--- Starting Graph Partitioning (no-L1 / naive mode) ---"
              << std::endl;

    PartitionContainer container;
    container.num_graph_vertices = graph->num_vertices;
    container.num_graph_edges = graph->num_edges;

    container.graph_out_degrees.resize(graph->num_vertices, 0);
    for (int u = 0; u < graph->num_vertices; ++u) {
        container.graph_out_degrees[u] =
            static_cast<uint32_t>(graph->offsets[u + 1] - graph->offsets[u]);
    }

    std::cout << "Global graph: " << graph->num_vertices << " vertices, "
              << graph->num_edges << " edges." << std::endl;
    std::cout << "[INFO] no-L1 mode: 1 little group (" << LITTLE_KERNEL_NUM
              << " pipelines) + 1 big group (" << BIG_KERNEL_NUM
              << " pipelines), max dst little=" << LITTLE_MAX_DST
              << " big=" << BIG_MAX_DST << std::endl;

    std::unordered_map<int, int> node_indegrees;
    for (int i = 0; i < graph->num_edges; ++i) {
        node_indegrees[graph->columns[i]]++;
    }

    std::vector<int> unique_dsts;
    unique_dsts.reserve(node_indegrees.size());
    for (const auto &kv : node_indegrees) {
        unique_dsts.push_back(kv.first);
    }
    std::sort(unique_dsts.begin(), unique_dsts.end(),
              [&node_indegrees](int a, int b) {
                  return node_indegrees[a] > node_indegrees[b];
              });
    std::cout << "[PHASE 1] " << unique_dsts.size()
              << " unique destination vertices (sorted by indegree)."
              << std::endl;

    const size_t total_dsts = unique_dsts.size();
    size_t little_dst_count =
        std::min(static_cast<size_t>(LITTLE_MAX_DST), total_dsts);
    if (little_dst_count == total_dsts) {
        little_dst_count = static_cast<size_t>(total_dsts * 0.8);
    }
    size_t big_dst_count =
        std::min(static_cast<size_t>(BIG_MAX_DST), total_dsts - little_dst_count);

    std::vector<int> little_ordered_dsts;
    std::vector<int> big_ordered_dsts;
    little_ordered_dsts.reserve(little_dst_count);
    big_ordered_dsts.reserve(big_dst_count);
    std::unordered_map<int, int> dst_to_partition;

    for (size_t i = 0; i < little_dst_count; ++i) {
        little_ordered_dsts.push_back(unique_dsts[i]);
        dst_to_partition[unique_dsts[i]] = 0;
    }
    for (size_t i = little_dst_count; i < little_dst_count + big_dst_count; ++i) {
        big_ordered_dsts.push_back(unique_dsts[i]);
        dst_to_partition[unique_dsts[i]] = 1;
    }

    std::cout << "[PHASE 2] Little: " << little_ordered_dsts.size()
              << " dsts, Big: " << big_ordered_dsts.size() << " dsts."
              << std::endl;

    std::vector<Edge> little_edges;
    std::vector<Edge> big_edges;
    little_edges.reserve(graph->num_edges);
    big_edges.reserve(graph->num_edges);

    for (int u = 0; u < graph->num_vertices; ++u) {
        for (int i = graph->offsets[u]; i < graph->offsets[u + 1]; ++i) {
            Edge edge;
            edge.src = u;
            edge.dest = graph->columns[i];
            edge.weight = graph->weights[i];

#if EDGE_PROP_COUNT > 0
            edge.props.resize(EDGE_PROP_COUNT, 0);
            const size_t prop_base = static_cast<size_t>(i) * EDGE_PROP_COUNT;
            for (size_t p_idx = 0; p_idx < EDGE_PROP_COUNT; ++p_idx) {
                edge.props[p_idx] = graph->edge_props[prop_base + p_idx];
            }
#endif

            auto it = dst_to_partition.find(edge.dest);
            if (it == dst_to_partition.end()) {
                std::cerr << "[ERROR] Destination vertex " << edge.dest
                          << " not in any partition!" << std::endl;
                std::exit(EXIT_FAILURE);
            }

            if (it->second == 0) {
                little_edges.push_back(std::move(edge));
            } else {
                big_edges.push_back(std::move(edge));
            }
        }
    }

    std::cout << "[PHASE 3] Little: " << little_edges.size()
              << " edges, Big: " << big_edges.size() << " edges."
              << std::endl;

    std::vector<int> global_to_local(static_cast<size_t>(graph->num_vertices), -1);

#include "process_partition.inc"

    PartitionDescriptor little_pd =
        process_partition(little_edges.data(), little_edges.size(),
                          little_ordered_dsts, true, LITTLE_KERNEL_NUM,
                          global_to_local);
    std::cout << "  Little: " << little_pd.num_vertices << " vertices, "
              << little_pd.num_dsts << " dsts, " << little_pd.num_edges
              << " edges -> " << little_pd.num_pipelines << " pipelines."
              << std::endl;

    PartitionDescriptor big_pd =
        process_partition(big_edges.data(), big_edges.size(), big_ordered_dsts,
                          false, BIG_KERNEL_NUM, global_to_local);
    std::cout << "  Big: " << big_pd.num_vertices << " vertices, "
              << big_pd.num_dsts << " dsts, " << big_pd.num_edges
              << " edges -> " << big_pd.num_pipelines << " pipelines."
              << std::endl;

    PartitionGroup little_group;
    little_group.group_id = 0;
    little_group.pipeline_offset = 0;
    little_group.num_pipelines = LITTLE_KERNEL_NUM;
    little_group.partitions.push_back(std::move(little_pd));

    PartitionGroup big_group;
    big_group.group_id = 0;
    big_group.pipeline_offset = 0;
    big_group.num_pipelines = BIG_KERNEL_NUM;
    big_group.partitions.push_back(std::move(big_pd));

    container.dense_groups.push_back(std::move(little_group));
    container.sparse_groups.push_back(std::move(big_group));
    container.num_dense_groups = 1;
    container.num_sparse_groups = 1;
    container.num_dense_partitions = 1;
    container.num_sparse_partitions = 1;

    container.dense_partition_order.push_back({0, 0});
    container.sparse_partition_order.push_back({0, 0});
    container.dense_partition_indices.resize(1);
    container.dense_partition_indices[0].push_back(0);
    container.sparse_partition_indices.resize(1);
    container.sparse_partition_indices[0].push_back(0);

    std::cout << "[SUCCESS] no-L1 partitioning complete: 1 dense + 1 sparse."
              << std::endl;
    return container;
}
