/**
 * graph_preprocess.cpp — No-L1 (naive) preprocess mode.
 *
 * Simplified 2-partition preprocessing without throughput-based repartitioning.
 * Distributes destination vertices by a fixed 80/20 ratio between little and
 * big partitions, sorted by indegree.
 *
 * This file is auto-generated by Graph.hls with no_l1_preprocess: true.
 * It reuses the normal partition formatter so the emitted host/kernel contract
 * stays consistent with standard preprocess mode.
 */
#include "graph_preprocess.h"

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <iostream>
#include <numeric>
#include <set>
#include <vector>

#if EDGES_PER_WORD <= 0
#error "EDGES_PER_WORD must be positive"
#endif

struct Edge {
    int src;
    int dest;
    int weight;
    std::vector<uint64_t> props;
};

static inline size_t pad_to_word(size_t n) {
    const size_t mod = n % EDGES_PER_WORD;
    return mod == 0 ? 0 : (EDGES_PER_WORD - mod);
}

PartitionContainer partitionGraph(const GraphCSR *graph,
                                  double /* big_edge_per_ms_per_pipe */,
                                  double /* little_edge_per_ms_per_pipe */) {
    std::cout << "--- Starting Graph Partitioning (no-L1 / naive mode) ---"
              << std::endl;

    PartitionContainer container;
    container.num_graph_vertices = graph->num_vertices;
    container.num_graph_edges = graph->num_edges;

    container.graph_out_degrees.resize(graph->num_vertices, 0);
    for (int u = 0; u < graph->num_vertices; ++u) {
        container.graph_out_degrees[u] =
            static_cast<uint32_t>(graph->offsets[u + 1] - graph->offsets[u]);
    }

    std::cout << "Global graph: " << graph->num_vertices << " vertices, "
              << graph->num_edges << " edges." << std::endl;
    std::cout << "[INFO] no-L1 mode: 1 little group (" << LITTLE_KERNEL_NUM
              << " pipelines) + 1 big group (" << BIG_KERNEL_NUM
              << " pipelines), max dst little=" << LITTLE_MAX_DST
              << " big=" << BIG_MAX_DST << std::endl;

    std::unordered_map<int, int> node_indegrees;
    for (int i = 0; i < graph->num_edges; ++i) {
        node_indegrees[graph->columns[i]]++;
    }

    std::vector<int> unique_dsts;
    unique_dsts.reserve(node_indegrees.size());
    for (const auto &kv : node_indegrees) {
        unique_dsts.push_back(kv.first);
    }
    std::sort(unique_dsts.begin(), unique_dsts.end(),
              [&node_indegrees](int a, int b) {
                  return node_indegrees[a] > node_indegrees[b];
              });
    std::cout << "[PHASE 1] " << unique_dsts.size()
              << " unique destination vertices (sorted by indegree)."
              << std::endl;

    const size_t total_dsts = unique_dsts.size();
    std::vector<std::vector<int>> little_partition_dsts;
    std::vector<std::vector<int>> big_partition_dsts;
    std::unordered_map<int, std::pair<int, size_t>> dst_to_partition;
    dst_to_partition.reserve(total_dsts);

    auto assign_chunk = [&](bool is_little, size_t start_idx, size_t count) {
        if (count == 0) {
            return;
        }
        auto &partition_list =
            is_little ? little_partition_dsts : big_partition_dsts;
        const size_t part_idx = partition_list.size();
        auto &chunk = partition_list.emplace_back();
        chunk.reserve(count);
        for (size_t i = 0; i < count; ++i) {
            const int dst = unique_dsts[start_idx + i];
            chunk.push_back(dst);
            dst_to_partition[dst] = {is_little ? 0 : 1, part_idx};
        }
    };

    size_t cursor = 0;
    if (total_dsts <= static_cast<size_t>(LITTLE_MAX_DST)) {
        size_t little_dst_count = static_cast<size_t>(total_dsts * 0.8);
        if (little_dst_count == 0 && total_dsts != 0) {
            little_dst_count = 1;
        }
        if (little_dst_count >= total_dsts && total_dsts > 1) {
            little_dst_count = total_dsts - 1;
        }
        const size_t big_dst_count = total_dsts - little_dst_count;
        assign_chunk(true, 0, little_dst_count);
        assign_chunk(false, little_dst_count, big_dst_count);
    } else {
        while (cursor < total_dsts) {
            const size_t little_take =
                std::min(static_cast<size_t>(LITTLE_MAX_DST), total_dsts - cursor);
            assign_chunk(true, cursor, little_take);
            cursor += little_take;
            if (cursor >= total_dsts) {
                break;
            }

            const size_t big_take =
                std::min(static_cast<size_t>(BIG_MAX_DST), total_dsts - cursor);
            assign_chunk(false, cursor, big_take);
            cursor += big_take;
        }
    }

    size_t little_total_dsts = 0;
    for (const auto &chunk : little_partition_dsts) {
        little_total_dsts += chunk.size();
    }
    size_t big_total_dsts = 0;
    for (const auto &chunk : big_partition_dsts) {
        big_total_dsts += chunk.size();
    }

    std::cout << "[PHASE 2] Little: " << little_total_dsts << " dsts across "
              << little_partition_dsts.size() << " partition(s), Big: "
              << big_total_dsts << " dsts across " << big_partition_dsts.size()
              << " partition(s)." << std::endl;

    std::vector<std::vector<Edge>> little_partition_edges(
        little_partition_dsts.size());
    std::vector<std::vector<Edge>> big_partition_edges(big_partition_dsts.size());

    for (int u = 0; u < graph->num_vertices; ++u) {
        for (int i = graph->offsets[u]; i < graph->offsets[u + 1]; ++i) {
            Edge edge;
            edge.src = u;
            edge.dest = graph->columns[i];
            edge.weight = graph->weights[i];

#if EDGE_PROP_COUNT > 0
            edge.props.resize(EDGE_PROP_COUNT, 0);
            const size_t prop_base = static_cast<size_t>(i) * EDGE_PROP_COUNT;
            for (size_t p_idx = 0; p_idx < EDGE_PROP_COUNT; ++p_idx) {
                edge.props[p_idx] = graph->edge_props[prop_base + p_idx];
            }
#endif

            auto it = dst_to_partition.find(edge.dest);
            if (it == dst_to_partition.end()) {
                std::cerr << "[ERROR] Destination vertex " << edge.dest
                          << " not in any partition!" << std::endl;
                std::exit(EXIT_FAILURE);
            }

            const auto &partition_info = it->second;
            if (partition_info.first == 0) {
                little_partition_edges[partition_info.second].push_back(
                    std::move(edge));
            } else {
                big_partition_edges[partition_info.second].push_back(
                    std::move(edge));
            }
        }
    }

    size_t little_total_edges = 0;
    for (const auto &chunk : little_partition_edges) {
        little_total_edges += chunk.size();
    }
    size_t big_total_edges = 0;
    for (const auto &chunk : big_partition_edges) {
        big_total_edges += chunk.size();
    }

    std::cout << "[PHASE 3] Little: " << little_total_edges
              << " edges, Big: " << big_total_edges << " edges." << std::endl;

    std::vector<int> global_to_local(static_cast<size_t>(graph->num_vertices), -1);

#include "process_partition.inc"

    PartitionGroup little_group;
    little_group.group_id = 0;
    little_group.pipeline_offset = 0;
    little_group.num_pipelines = LITTLE_KERNEL_NUM;

    PartitionGroup big_group;
    big_group.group_id = 0;
    big_group.pipeline_offset = 0;
    big_group.num_pipelines = BIG_KERNEL_NUM;

    for (size_t part_idx = 0; part_idx < little_partition_dsts.size();
         ++part_idx) {
        PartitionDescriptor little_pd =
            process_partition(little_partition_edges[part_idx].data(),
                              little_partition_edges[part_idx].size(),
                              little_partition_dsts[part_idx], true,
                              LITTLE_KERNEL_NUM, global_to_local);
        std::cout << "  Little partition " << part_idx << ": "
                  << little_pd.num_vertices << " vertices, "
                  << little_pd.num_dsts << " dsts, " << little_pd.num_edges
                  << " edges -> " << little_pd.num_pipelines << " pipelines."
                  << std::endl;
        little_group.partitions.push_back(std::move(little_pd));
    }

    for (size_t part_idx = 0; part_idx < big_partition_dsts.size(); ++part_idx) {
        PartitionDescriptor big_pd =
            process_partition(big_partition_edges[part_idx].data(),
                              big_partition_edges[part_idx].size(),
                              big_partition_dsts[part_idx], false,
                              BIG_KERNEL_NUM, global_to_local);
        std::cout << "  Big partition " << part_idx << ": " << big_pd.num_vertices
                  << " vertices, " << big_pd.num_dsts << " dsts, "
                  << big_pd.num_edges << " edges -> " << big_pd.num_pipelines
                  << " pipelines." << std::endl;
        big_group.partitions.push_back(std::move(big_pd));
    }

    container.dense_groups.push_back(std::move(little_group));
    container.sparse_groups.push_back(std::move(big_group));
    container.num_dense_groups = 1;
    container.num_sparse_groups = 1;
    container.num_dense_partitions =
        static_cast<unsigned int>(container.dense_groups[0].partitions.size());
    container.num_sparse_partitions =
        static_cast<unsigned int>(container.sparse_groups[0].partitions.size());

    container.dense_partition_indices.resize(1);
    container.sparse_partition_indices.resize(1);
    for (size_t part_idx = 0; part_idx < container.dense_groups[0].partitions.size();
         ++part_idx) {
        container.dense_partition_order.push_back({0, part_idx});
        container.dense_partition_indices[0].push_back(part_idx);
    }
    for (size_t part_idx = 0;
         part_idx < container.sparse_groups[0].partitions.size(); ++part_idx) {
        container.sparse_partition_order.push_back({0, part_idx});
        container.sparse_partition_indices[0].push_back(part_idx);
    }

    std::cout << "[SUCCESS] no-L1 partitioning complete: "
              << container.num_dense_partitions << " dense + "
              << container.num_sparse_partitions << " sparse partition(s)."
              << std::endl;
    return container;
}
